defaults: &defaults
  adapter: mysql2
  encoding: utf8mb4
  url: <%= ENV.fetch('DATABASE_URL', 'mysql2://root:@localhost:3306/rdiplomacy_dev?reconnect=true') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5).to_i %>
  reconnect: true

development:
  <<: *defaults

test:
  <<: *defaults
  database: "<%= ENV.fetch('TEST_DB_NAME', 'rdiplomacy_test') %>"

production: &production
  <<: *defaults
  url: <%= ENV['DATABASE_URL'] %>

staging:
  <<: *production

integration:
  <<: *production
